# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  displayName: Prepare Sonar Cloud
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'laikha'
    scannerMode: 'MSBuild'
    projectKey: 'laikha_PorExtenso'
    projectName: 'PorExtenso'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: Update Nuget Packages
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build Code
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Test Fase
  inputs:
    solution: '$(solution)' 
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis by Azure'

- task: reportgenerator@5
  displayName: 'Jacoco'
  inputs:
    codeCoverageTool: 'JaCoCo'
    reports: '$(Build.SourcesDirectory)\Tests\CodeCoverage.xml'
    targetdir: '$(Build.SourcesDirectory)\Tests\CoverageReport'
    verbosity: 'Verbose'
    title: 'Jacoco'

- task: PublishCodeCoverageResults@1
  displayName: 'Cobertura Report'
  inputs:
    codeCoverageTool: JaCoCo
    summaryFileLocation: '$(Build.SourcesDirectory)\Tests\CodeCoverage.xml'
    pathToSources: '$(Build.SourcesDirectory)'
    reportDirectory: '$(Build.SourcesDirectory)\Tests\CoverageReport'
    title: 'JaCoCo Report'

- task: SonarCloudPublish@1
  displayName: Publish Sonar
  inputs:
    pollingTimeoutSec: '300'